### PR TITLE
Add firmware version string

### PR DESCRIPTION
**Pull request by bigdinotech**

### CODE REVIEW

**Comment by bigdinotech** [comment]
@SidLeung @eriknyquist please review

**Comment by eriknyquist** [comment]
Dino

**Comment by eriknyquist** [comment]
fill

**Comment by eriknyquist** [comment]
in

**Comment by eriknyquist** [comment]
the

**Comment by eriknyquist** [comment]
fields

**Comment by eriknyquist** [comment]
please

**Pull request merged**
